version: 2
updates:
  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain NPM dependencies.
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
